#ifndef FUNC_CODE_H
#define FUNC_CODE_H

#define FUNC_userspace_liteapi_get_node_id 1
#define FUNC_userspace_liteapi_join 2
#define FUNC_userspace_liteapi_alloc_remote_mem 3
#define FUNC_userspace_liteapi_rdma_write 4
#define FUNC_userspace_liteapi_rdma_read 5
#define FUNC_userspace_liteapi_send_reply_imm_fast 6
#define FUNC_userspace_liteapi_receive_message_fast 7
#define FUNC_userspace_liteapi_reply_message 8
#define FUNC_userspace_liteapi_register_application 9
#define FUNC_userspace_liteapi_dist_barrier 10
#define FUNC_userspace_liteapi_query_port 11
#define FUNC_userspace_liteapi_alloc_local_mem 12
#define FUNC_userspace_liteapi_free_local_mem 13

#endif
